runtime: python
env: flex
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app

#runtime_config:
#  python_version: 3.7

#runtime_config:
#  operating_system: ubuntu22
#  runtime_version: 3.10

runtime_config:
  operating_system: ubuntu22
  python_version: 3.10

manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10
